### PR TITLE
Many love2d functions added

### PR DESCRIPTION
**Pull request by MrcSnm**
Those functionalities were added only for onelua, because it worked on my PC, and they were added based on my project from love2d, I didn't adapt a thing of my original code, except the button handling

- 3 Tools for easier working with vita 
- Support for basic operations from love2d (quads [required for animations/spritesheets], printf [aligning functions])
- PS Vita callbacks (onLiveArea and onResume)
- Negative scaling correctly works
- Scaled quad works (Although it lags a bit on the first scale call, as it requires to load a new texture (DOESN'T SUPPORT SCALE TWEENS)
- Implemented touch/mouse functionality for vita, out-of-the-box, mouse is defaulted as the most recent touch
- Support for main framebuffer transformation (scaling and translation, clipping is incomplete), now it is much easier to mantain the original resolution, just call love.graphics.scale(PS_VITA_WIDTH / YOUR_RESOLUTION_WIDTH, PS_VITA_HEIGHT / YOUR_RESOLUTION_HEIGHT)
- Added support for setting default MAG and MIN filtering
- Some bugs were workarounded (as font would be ugly after screen.textwidth calls)
- Issues documentation
- Added some boilerplate functions for not conflicting with original source code
- Added reload command for vita (Nice for testing) [HOLD LEFT, UP, SQUARE, TRIANGLE, L and PRESS R]

This was enough for my current game fully working on it, I'll try adding more functionalities as I make love2d games

### CODE REVIEW

**Comment by LukeZGD** [comment]
This is a lot more than what I could have ever done for LOVE-WrapLua, thank you for the contributions!

I tested it with DDLC-LOVE and there are some problems to be fixed before I can merge:
- When x and/or y value is not given in love.graphics.draw, it gives an error (it should default to 0), I fixed this in `graphics.lua`, lines 345 & 346:
```
_x = xOrQuad or 0
_y = y or 0
```
- The printed text is lower down, not sure why (also happens with printf):

- Going to the live area doesn't work for me (not sure if relevant but I have 3.65 on my Vita)
- Also I would suggest changing the soft-reset combo to something a bit easier (like L+R+Down+Start) as the current one can be pretty hard to press on a controller

I may or may not be able to test the other functions added as I'm not very experienced with Love2D myself

**Comment by MrcSnm** [comment]
How you're not able? Is it not going back when pressing the Home button or the callback is not working? I don't know if it is the same oddities, but in my Vita, when I press the Home button, the 2 analogs x and y only register 0, without flickering. I use this as an info that Home was pressed, if you could, please check if your vita does the same

**Comment by LukeZGD** [comment]
> How you're not able? Is it not going back when pressing the Home button or the callback is not working? I don't know if it is the same oddities, but in my Vita, when I press the Home button, the 2 analogs x and y only register 0, without flickering. I use this as an info that Home was pressed, if you could, please check if your vita does the same

Oh I see, I just checked and they are not 0 for me but around -8 to +8, might be something to consider as analogs can be pretty sensitive

**Comment by MrcSnm** [comment]
> > How you're not able? Is it not going back when pressing the Home button or the callback is not working? I don't know if it is the same oddities, but in my Vita, when I press the Home button, the 2 analogs x and y only register 0, without flickering. I use this as an info that Home was pressed, if you could, please check if your vita does the same
> 
> Oh I see, I just checked and they are not 0 for me but around -8 to +8, might be something to consider as analogs can be pretty sensitive

Probably I'll just remove the callbacks for now, while I can't do it, but I'll mantain them commented.
As for the text, I found that there is a misbehavior between print in love and onelua. OneLua doesn't care about the font size when printing, it starts in the correct X coordinate, but the Y coordinate, if you increase the font size, it increases in the top direction instead of bottom, the pivot point is (0, 1) , so you're probably handling yourself that behavior. what I did was setting the pivot point to (0,0), the problem I found right now is another issue with OneLua, an inconsistency about the font, it's coordinate does not just have a strange pivot, it has too one Y offset(which probably is the default font size), so I'm trying to find it right now and update it

**Comment by MrcSnm** [comment]
Okay, take a look, I believe that it is behaving as someone would expect, the Y offset is the 18.5 value, subtracting (18.5 - currentFontHeight) will get you to the pivot (0,0)
Updated to your reset command and removed custom livearea while onelua team does not update

**Comment by LukeZGD** [comment]
Tested and it now works nicely, will be merging now

**Comment by LukeZGD** [comment]
Tested and things work nicely, will be merging now

**Comment by LukeZGD** [comment]
Tested and it works nicely, will be merging now

**Pull request merged**
